name: Generate


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Generate:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2    
      - name: Required package Install
        run: sudo apt-get install wget zip unzip p7zip p7zip-full p7zip-rar
      - name: Stock ROM Files Downalod
        run: wget https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-large-zip-file.zip -O sam.zip
      - name: TWRP Device Tree Generate
        run: |
         unzip sam.zip
         ls
      
      - uses: actions/setup-python@v2.3.1
      - name: Setup Python
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python -m pip install twrpdtgen

         
