name: Generate


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Generate:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2    
      - name: Twrp Device Tree Generate
        run: |
         sudo apt-get install wget zip unzip p7zip p7zip-full p7zip-rar
         wget https://dl.sam-fw.cf/v2/IxJCDiMnLiMeMRQcHi88ADsvLAISNh4lFzssIDs2ByAzMUEgOzEUQDMQMCMBOyw/I0AsFCERHwwvAxUGLyUHCA8nHh0jMQIBDTAzMRInPhQeOEEXNDsCADQ2BgUvCywnEgAwBiMwFTADNi8jAzsGCyEAHwsjJB4vMgc+IDw7HgE0EQYSMjhBDiFABkIjCyI/Iws8MQEWCDAeCw0xCREHOTQbIyshAD4OIQAGLC44Hiw0ER4OMiUzLDIlDSs8AD4fJhsGOg8HCkA8AywnCRc+Di8LBxAzBy4RDxYpKTwkHjUeBylCJgceKTIXIUAJER4OMi8+AwMSMCAjCyJAMyw+QQMsHiYNAwU5HjEhPBcHOz8NMC9BIyw+ETwXIysPESw5JhsGQDIlMy0SJzMhMgMvBy87Ljo7JA0/OywsFDIEMAABCB4/OwsHIR4sAgojCwdCJhYIACMkFSQjJCMAAQMjEw== -O sam.zip
      - name: Twrp Device Tree Generate3
        run: |
         unzip sam.zip
         ls
         7z e *.tar.md5
         ls
         
